name: Release

# testing on a branch for now

on:
  push:
    branches:
      - test-release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install
        uses: ./.github/actions/install
        with:
          transcrypt_password: ${{ secrets.transcrypt_password }}

      - name: Install playwright
        run: npx playwright install
        
      - name: Test
        run: yarn test

      - name: Publish
        # just testing for now so --skip-publish
        run: yarn release:beta:dirty --ci --tamagui-git-user --skip-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    # needs: release

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          prerelease: false
