name: Deploy Migrations to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      PRODUCTION_PROJECT_ID: akrzjiwwabjhzbvvnypu

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1

      - run: |
          cd code/tamagui.dev
          supabase link --project-ref $PRODUCTION_PROJECT_ID
          supabase db push
